BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBB

BBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBB

BB BBBBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
    BBB BBB BB BBBBBBBBBBBBBBBBBBBBB
    XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    BBBBBB
XXXXXX
BBBBB
XXXX XXXXXXXXXXXXXXXXXX

  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      BB BBBBBBB
      XX XXXXXXXXXXXXXXXXXX XXXX XXXX gettext(u'Update Invoice') XXXX
      BBBB
      XX XXXXXXXXXXXXXXXXXX XXXX XXXX X  gettext(u'Create Invoice') XXXX
      BBBBB
    XXXXXX
      XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
              
              
              XXXXXX XXXXXXXXXXXXXXXXXXXX
                
              XXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
              XX XXXXXXXXXXXXXFFFFXXXX
              BBBBB
              
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
              
              
              XXXXXX XXXXXXXXXXXXXXXXXXXX
                
              XXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
              XX XXXXXXXXXXXXXFFFFXXXX
              BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
               
              XXXXXX XXXXXXXXXXXXXXXXXXXX
                
              XXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
              XX XXXXXXXXXXXXXFFFFXXXX
              BBBBB
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
              
              XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Get the Purchase Order Number for your invoice from your contact/buyer at Eventbrite') XX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXX
              
              XXXXXX XXXXXXXXXXXXXXXXXXXX
                
              XXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXX
                 gettext(u'Eventbrite entity') 
                XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Eventbrite company to which you bill') XX
                  XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXX
              XXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                BBB BBBBBBBBB BB BBBBBBBBBBB
                XXXXXXX XXXXXXXXXXXXXXXXXX
                BBBBBB
              XXXXXXXXX
            XXXXXX
            BB BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                 
                XXXXXX XXXXXXXXXXXXXXXXXXXX
                  
                XXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBBBBB
                XXXXXX XXXXXXXXXXXXXXXXXXXFFFFXXXXXXXX
                BBBBB
            XXXXXX
            BBBBB
          XXXXXX
          XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
               
              XXXXXX XXXXXXXXXXXXXXXXXXXX
                
              XXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBBBB
              XX XXXXXXXXXXXXXFFFFXXXX
              BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                
              
              XXXXXX XXXXXXXXXXXXXXXXXXXX
                
              XXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBBBBBB
              XX XXXXXXXXXXXXXFFFFXXXX
              BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
               
              XXXXXX XXXXXXXXXXXXXXXXXXXX
                
              XXXXXXXX
              BB BBBBBBBBBBBBBBBBBB
              XX XXXXXXXXXXXXXFFFFXXXX
              BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
               
              XXXXXX XXXXXXXXXXXXXXXXXXXX
                
              XXXXXXXX
              BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
              XX XXXXXXXXXXXXXFFFFXXXX
              BBBBB
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXX XXXX XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Invoice File') XXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXX
                    
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Choose file') XXXXXXXX
                  XXXXXX
                XXXXXX
          XXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBB
            BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBB
              XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
                
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX
              XXXXXX
            BBBBBB
          BBBBB
        XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX
          XXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX
             gettext(u'Submit') 
          XXXXXXXXX
          BB BBBBBBB
          XX XXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXX gettext(u'Cancel') XXXX
          BBBB
          XX XXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXX gettext(u'Cancel') XXXX
          BBBBB
        XXXXXX
        BBBBBBBBBB
      XXXXXXX


  XXXXXX
XXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXX  X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
      XXXXXX XXXXX
    XXX
  XXX

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX

  XXXXXXXXXX XX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX

XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
  X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X X X X XX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX
X
XXXXXXXXX
BBBBBBBB
