BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBB BBBB
BBBB BB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBB


BBBBBBBBBB

XXXX XXXXXXXXXX XXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX
    BB BBBBBBBB
      BBB BBBBBBB BB BBBBBBBB
          XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXXXXX
            
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX
          XXXXXX
        BBBBBB
      BBBBBXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXXX gettext(u'Invoice #') XXXXXXXXX
        
        XXXXXXXX gettext(u'Date:') XXXXXXXXX
        FFFFFFFFFFFFFFFF
        BB BBB BBBBBBBB BBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBB
        XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX
           gettext(u'Edit info') 
        XXXX
        BBBB BBBBBBBB BBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX
           gettext(u'Edit info') 
        XXXX
        BBBBB
        XXXXX XXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXX XXXXXXXXX XXXXXXXX gettext(u'Download Invoice') XXXX
          XXXXXXXX gettext(u'Status') XXXXXXXXXX
          BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBB
          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          BBBBB
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXX gettext(u'From: ') XXXXX
            XXXXX
              XXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXX XXXXXX
            XXXXX XXXXXX
            XXXXXXXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXX gettext(u'Details:') XXXXX
            XXXXXXXXXXXXX gettext(u'Taxpayer Identification Number:') XXXXXXXXX XXXXXX
            XXXXXXXXXXXXX gettext(u'Payment Option:') XXXXXXXXX XXXXXX
            XXXXXXXXXXXXX gettext(u'PO number:') XXXXXXXXX XXXXXX
            BB BBBBBBBBBBBBBBBBBB
            XXXXXXXXXXXXX gettext(u'Workday ID:') XXXXXXXXX XXXXXX
            BBBBB
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX
            XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
              XXXXXXX
                XXXX
                  XXX XXXXXXXXXXXXX
                    XXXXXXXX gettext(u'Net amount: ') XXXXXXXXX
                  XXXXX
                  XXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX 
                  XXXXX
                XXXXX
                XXXX
                  XXX XXXXXXXXXXXXX
                    XXXXXXXX gettext(u'Tax Liens') XXXXXXXXX
                  XXXXX
                  XXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX 
                  XXXXX
                XXXXX
                XXXX
                  XXX XXXXXXXXXXXXX
                    XXXXXXXX gettext(u'Total') XXXXXXXXX
                  XXXXX
                  XXX XXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXX 
                  XXXXX
                XXXXX
              XXXXXXXX
            XXXXXXXX

          XXXXXX
        XXXXXX
      XXXXXX
     BB BBBBB
     XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
       XXXX XXXXXXXXXXXX
         XXXX XXXXXXXXXX XXXXXX
           XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
             BBBBBBBBBB
             BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
             XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXX XXX XXXXXXXXXXX XXXXXXXXX gettext(u'Reject') XXXXXXXXX
             BBBBB
            BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
                XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXX gettext(u'Pay') XXXXXXXXX
            BBBBB
            XXXXXXX
          XXXXXX
          BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXX
                BBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX gettext(u'Approve') XXXXXXXXX
                      XXXXXX
                  XXXXXX
                XXXXXXX
            XXXXXX
          BBBBB
          BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBB
         XXXX XXXXXXXXXXXX
           XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXX
             BBBBBBBBBB
             XXXX XXXXXXXXXXXXXXXXXX XXXXXX
               XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX
               XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX gettext(u'In Progress') 
                 XXXXXXXXX
               XXXXXX
             XXXXXX
           XXXXXXX
         XXXXXX
         BBBBB
         BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXX XXXXXXXXXXXX 
              XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Request Changes') XXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBXX
              BBBBBBBBBB
              XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXX gettext(u'Send Request') XXXXXXXXX
            XXXXXXX
          XXXXXX
         BBBBB

        XXXXXX
        XXXX XXXXXXXXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXX
            XXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXX gettext(u'Invoice History') XXXXXXXXXXX
          XXXXXX
        XXXXXX
     XXXXXX
    BBBBB
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXX XXX XXXXXXXX XXXXXXX XXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXX gettext(u'Recent updates') XXXXX
      XXXXX
        XXXX XXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXX XX

            XXXX XXXXXXXXXX XXXXXX
              XXXX gettext(u'Make a comment') XXXXX
              XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXX
                  XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXX XXXXXX
                XXXX XXXXXXXXXXX XXXX XXXXXXXXXX
                  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX gettext(u'Post a comment') XXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXX
                      XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX gettext(u'Choose a file') XXXXXXXX
                    XXXXXX
                  XXXXXX
                XXXXXX
              XXXXXX
              XXXXXXX
            XXXXXX
            BBBBB
          XXXXXX
        XXXXXX
        BBB BBBBBBB BB BBBBBBBB
        XXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXX XXXX XXXX XXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX
            BB BBB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBB
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Administrator') XXXXXXX
            BBBBB
            XX XXXXXXXXXXXXXXXXXX XXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXX XXXX XXXXXX
              XX XXXXXXXXXXX XXXXXX gettext(u'Attachment: ') XXXX
              XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
              XXXX
            XXXXXX
            BBBBB
            XX XXXXXXXXXXXXX FFFFFFFFFFFFXXXX

          XXXXXX
        XXXXXX
        BBBBBB
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX

  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXX
XXXXXXXXX
BBBBBBBB
