# 25 * 1014 * 1024
TAXPAYER_BANK_ACCOUNT_MAX_SIZE_FILE = 26214400

TAXPAYER_BANK_ACCOUNT_ALLOWED_FILE_EXTENSIONS = ['.pdf']

TAXPAYER_STATUS = [
    ("ACTIVE", "Active"),
    ("CHANGE REQUIRED", "Change required"),
    ("PENDING", "Pending"),
]
TAXPAYER_STATUS_AP = [
    'CHANGE REQUIRED',
    'PENDING',
]
