CURRENCIES = [
    ('ARS', 'ARS'),
    ('USD', 'USD')
    ]

INVOICE_STATUS_APPROVED = 'APPROVED'
INVOICE_STATUS_NEW = 'NEW'
INVOICE_STATUS_CHANGES_REQUEST = 'CHANGES REQUEST'
INVOICE_STATUS_REJECTED = 'REJECTED'
INVOICE_STATUS_PAID = 'PAID'

INVOICE_STATUS = [
    ('1', INVOICE_STATUS_APPROVED),
    ('2', INVOICE_STATUS_NEW),
    ('3', INVOICE_STATUS_CHANGES_REQUEST),
    ('4', INVOICE_STATUS_REJECTED),
    ('5', INVOICE_STATUS_PAID),
]

ARS_INVOICE_TYPES = [
    ('A', 'A'),
    ('C', 'C'),
]


