# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-09 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20191009_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='user',
            index_together=set([('email',)]),
        ),
    ]
