# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-30 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_user_is_ap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_AP',
        ),
    ]
