language: python
python:
  - "3.7.4"
cache: pip
env:
  - DJANGO_VERSION=1.11.24
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run --source='.' ./manage.py test
after_success:
  - coveralls
