BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
BBBBBBB BBBBBBBBBBBBB
XXX XXXXXXXXXXXXXXXXXX XXXXXX
     gettext(u'Create a new admin') 
XXXXX
XXXXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                
                
                XXXXXX XXXXXXXXXXXXXXXXXXXX
                    
                XXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBB
                XX XXXXXXXXXXXXXFFFFXXXX
                BBBBB
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXXXX gettext(u'Role:') XXXXXXXX
                
                XXXXXX XXXXXXXXXXXXXXXXXXXX
                    
                XXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX gettext(u'Create') XXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXX gettext(u'Cancel') XXXX
    XXXXXX
XXXXXXX
BBBBBBBB