BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBB
BBBB BBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBX XX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX gettext(u'ERROR') XXXXX
          XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'If you are a supplier please:') XXXXX
          XX XXXXXXXXXX XXXXXX XXXXXXXXXXX
              XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBXXXXXXXX
               gettext(u'Login with') 
              XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXX XXXXXXX
          XXXX
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBXX  gettext(u'Login home')  XXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXX XXXXXX
      XXXX XXXXXXXXXXXX
          XX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Language') XXXXX
          BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXX XXXXXX
        X XXXX XXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXXXXX
          XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBXXXXXXXX
           gettext(u'AP login') 
        XXXX
      XXXX
    XXXXXX
  XXXXXX
XXXXXXXXX
BBBBBBBB
