BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBB
BBBB BBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBX XX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXX XXXXXXXXXX
  XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXX XXXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXX XX
      XXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Supplier Sign in') XXXXX
          XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXX XXXX XXXXX
              XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBXXXXXXXX
               gettext(u'Login with') 
              XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXX XXXXXXX
            XXXX
          XXXXXX
          XXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXX XXXXXXXXXXXX gettext(u'Choose your language') XXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
        X XXXX XXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXX XXXX
          XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBXXXXXXXX
           gettext(u'Login as Eventbrite Employee') 
        XXXX
    XXXXXX
  XXXXXX
XXXXXXXXX

BBBBBBBB

BBBBB BBBBBBB
XXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Welcome to BriteSU')  XXXXX

BBBBBBBB