BBBB BBBB


XXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX XX XXXXXX gettext(u'Attachments and tax condition') XXXXX
XXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XX XXXXXXX gettext(u'Only PDF files are accepted') XXXXXX
XXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XX XXXXXXX  gettext(u'Mandatory attachments')  XXXXXX

XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XX XXXXXXXXXXXX
XXXX XXXXXXXXXX XXXXXXXXXX XX XXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XX XXXXXXXXXXXX
XXXX XXXXXXX XXX XXXXXXXXXX XX XXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XX XXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XX XXXXXXXXXXXX

XXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX XX XXXX XXXXXXX  gettext(u'Optional Attachments')  XXXXXX

XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXX
XXXX XXXXXXX XXX XXXXXXXXXX XX XXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXX
XXXX XXXXXXX XXX XXXXXXXXXX XX XXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XX XXXXXXXX
XXXX XXXXXXX XXX XXXXXXXXXX XX XXXXXXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXX XX XXXXXXXX
XXXX XXXXXXX XXX XXXXXXXXXX XX XXXXXXXXXXXXXXXX