BBBB BBBB


    XXX XXXXXXXXXXXXXXX XXX XXXXXXXXXX gettext(u'Bank Info') XXXXX
    XXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX gettext(u'Enter your bank account details') XXXXX

    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXX XXXXXXX gettext(u'Previous') X XX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX  XXXXXXXXXXX XXXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Next') X XX
