BBBB BBBB
    XXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XXX XXX XXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXX gettext(u'Previous') X XX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX  XXXXXXXXXXX XXXXXXXXXXXXX XXXX XXXXXXX gettext(u'Next') X XX
    
