BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBB
BBBB BBBBBB

XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

BBBBBBBB

BBBBB BBBBBBB
BBBBBBB BBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB



XXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    XXX XXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
        XXXXXXXX XXXXXXXXX
        XXXXXXX XXXXXXXXX XXX XXXXXXXXXXXXXXXX
    XXXXX

    BBB BBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXX XXXXXXXXXXXXXXXXXXXX
                
            XXXXXXXX
            
    BBBBBB

    XXXXXXXXX XXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXX  gettext(u'Taxpayer Info')  XXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXX XXXXXXXXXXX XXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX XXXXXXXXXXX
                     
                XXXXXX
                XXXX XXXXXXXXXXXX XXXXXXXXXXX
                    
                XXXXXX
            XXXXXXXX
        BBBBBB

        XXX XXXXXXXXXXXXXXX XXXXXXX  gettext(u'Address Info')  XXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX

        XXX XXXXXXXXXXXXXXX XXXX XXXXXXX  gettext(u'Contact Info')  XXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX  XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXX gettext(u'Next') X XX
    XXXXXXXXXXX

    XXXXXXXXX XXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXXXXXXX

    XXXXXXXXX XXXXXXXX
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'Previous') X XX
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX gettext(u'Submit') X XX
    XXXXXXXXXXX
XXXXXXX

XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB