# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-02 19:26
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD')], max_length=200)),
                ('status', models.CharField(choices=[('1', 'APPROVED'), ('2', 'NEW'), ('3', 'CHANGES REQUEST'), ('4', 'REJECTED'), ('5', 'PAID')], default='NEW', max_length=40)),
                ('po_number', models.CharField(help_text='ex: 12341234', max_length=200)),
                ('invoice_date', models.DateField()),
                ('invoice_date_received', models.DateTimeField(auto_now=True)),
                ('invoice_file', models.FileField(blank=True, upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceArg',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices_app.Invoice')),
                ('invoice_number', models.CharField(max_length=20)),
                ('invoice_type', models.CharField(choices=[('A', 'A'), ('C', 'C')], max_length=200)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('vat', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            bases=('invoices_app.invoice',),
        ),
    ]
