# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-05 17:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import utils.file_validator


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='invoice_file',
            field=models.TextField(max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.file_validator.FileSizeValidator(limit_size=5242880)], verbose_name='Invoice File'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_file',
            field=models.FileField(upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.file_validator.FileSizeValidator(limit_size=5242880)], verbose_name='Invoice File'),
        ),
    ]
