# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-24 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='tax_payer',
            new_name='taxpayer',
        ),
        migrations.RenameField(
            model_name='taxpayer',
            old_name='tax_payer_state',
            new_name='taxpayer_state',
        ),
    ]
