# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-24 15:36
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('ARS', 'ARS'), ('USD', 'USD')], max_length=200)),
                ('status', models.CharField(choices=[('1', 'NEW'), ('2', 'APPROVED'), ('3', 'CHANGES REQUEST'), ('4', 'REJECTED'), ('5', 'PAID')], default='NEW', max_length=40)),
                ('po_number', models.CharField(max_length=200)),
                ('invoice_date', models.DateTimeField()),
                ('invoice_date_received', models.DateTimeField(auto_now=True)),
                ('invoice_file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceArg',
            fields=[
                ('invoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices_app.Invoice')),
                ('invoice_number', models.CharField(max_length=20)),
                ('invoice_type', models.CharField(choices=[('A', 'A'), ('C', 'C')], max_length=200)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('vat', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            bases=('invoices_app.invoice',),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices_app.TaxPayer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
