# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-07 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices_app', '0001_initial'),
        ('supplier_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='taxpayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier_app.TaxPayer'),
        ),
    ]
