# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-12 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices_app', '0001_initial'),
        ('supplier_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_eb_entity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supplier_app.EBEntity'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxpayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier_app.TaxPayer'),
        ),
    ]
