# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaxPayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workday_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaxPayerState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tax_payer_state', models.CharField(default='Pendiente', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaxPayerArgentina',
            fields=[
                ('taxpayer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices_app.TaxPayer')),
                ('razon_social', models.CharField(max_length=200)),
                ('cuit', models.CharField(max_length=200)),
            ],
            bases=('invoices_app.taxpayer',),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='tax_payer_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices_app.TaxPayerState'),
        ),
        migrations.AddField(
            model_name='address',
            name='tax_payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices_app.TaxPayer'),
        ),
    ]
