# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-25 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0002_auto_20190925_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(help_text='ex: 12341234', max_length=200),
        ),
    ]
