# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0002_auto_20190923_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('account_type', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=200)),
                ('identifier', models.CharField(max_length=200)),
                ('taxpayer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='invoices_app.TaxPayer')),
            ],
        ),
    ]
