# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-13 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0003_auto_20191106_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
