# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-03 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0002_auto_20191003_1252'),
        ('invoices_app', '0003_auto_20191003_1252'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set([('taxpayer', 'invoice_number')]),
        ),
    ]
