# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-12 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0003_auto_20191112_1452'),
        ('invoices_app', '0003_auto_20191106_1457'),
    ]

    operations = [
    ]
