# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-02 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0005_auto_20200601_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='new_comment_from_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='new_comment_from_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
