# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-16 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0006_auto_20200602_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='workday_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='workday_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
