# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-07-24 13:18
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0007_auto_20200616_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvoice',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Net amount'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax Liens'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Net amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax Liens'),
        ),
    ]
