# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-07-23 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_app', '0007_auto_20200616_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='historicalinvoice',
            name='vat',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vat',
        ),
    ]
