BBBB BBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXX

        BB BBBBBBBBBBBBBBBBBBB
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXX
        BBBB
            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX
        BBBBB

	XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX                
        XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Approve') X XXXXXXXXXXXXXX
    XXXXXX                
XXXXXXX
