BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
BBBBBBB BBBBBBBBBBBBB
    XXX XXXXXXXXXXXXXXXXXX XXXXXX
         gettext(u'Create a new company') 
    XXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXX gettext(u'Name') XXXXX
                XXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXX XXXXXXXXXXXXX
                    XXXX gettext(u'Description') XXXXX
                XXXXXX
                    XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Create Company') X XXXXXXXXXX XXXXXXXXXXX XXXXX
            XX XXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBXX gettext(u'Cancel') XXXX
        XXXXXXX
    XXXXXX


BBBBBBBB
