BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBB
BBBB BBBBBB
BBBBBBBB

BBBBB BBBBBBB
BBBBBBB BBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXX
        XXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Company List') XXXXX
    XXXXXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXX gettext(u'Search by name') XXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                XXXXXX
            XXXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XX
            XXXXXX XXXXXXXXX
                XXX XXXXXXXXXX XXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX gettext(u'Name') XXXXX
                    XXX XXXXXXXXXXXXXX gettext(u'Description') XXXXX
                    XXX XXXXXXXXXXXXXX gettext(u'Email Invitation') XXXXX
                XXXXX
            XXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXX
                BBB BBBBBBB BB BBBBBBBBBBB
                XXX XXXXXXXXXX XX
                    XXX XXXXXXXXXXXX XX
                        XXXX XXXXXXXXX
                            XXX XXXXXXXXXX XXXXXXX
                        XXXXXX
                        
                    XXXXX
                    XXX XXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXX
                    XXXXX
                    XXX XXXXXXXXXXXX XXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                            BBBBBBBBBB
                            XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXX X XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                            XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                                     gettext(u'English') 
                                XXXXXXXXX
                                XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
                                     gettext(u'Spanish') 
                                XXXXXXXXX
                                XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
                                     gettext(u'Portuguese') 
                                XXXXXXXXX
                            XXXXXXXXX
                            XXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX gettext(u'Invite') XX
                        XXXXXXX
                    XXXXX
                XXXXX
                BBBBBB
            XXXXXXXX
        XXXXXXXX
    XXXXXX
XXXXXX

BBBBBBBB