BBBB BBBB
XXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
    BBBBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX                
    XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'Deny') XXX
XXXXXXX