# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-12 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayercomment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_app.Company'),
        ),
        migrations.AddField(
            model_name='historicaltaxpayerargentina',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier_app.Company'),
        ),
        migrations.AddField(
            model_name='historicaltaxpayerargentina',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltaxpayer',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier_app.Company'),
        ),
        migrations.AddField(
            model_name='historicaltaxpayer',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbankaccount',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbankaccount',
            name='taxpayer',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier_app.TaxPayer'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='taxpayer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier_app.TaxPayer'),
        ),
        migrations.AddField(
            model_name='companyuserpermission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_app.Company'),
        ),
        migrations.AddField(
            model_name='companyuserpermission',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyuniquetoken',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_app.Company'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='taxpayer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supplier_app.TaxPayer'),
        ),
        migrations.AddField(
            model_name='address',
            name='taxpayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_app.TaxPayer'),
        ),
    ]
