# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-31 19:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='witholding_taxes_file',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Certificate of no tax withholding of Tax liens, income or SUSS'),
        ),
        migrations.AlterField(
            model_name='taxpayerargentina',
            name='witholding_taxes_file',
            field=models.FileField(blank=True, null=True, upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Certificate of no tax withholding of Tax liens, income or SUSS'),
        ),
    ]
