# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-25 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='pdf_file_received',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
