# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-31 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayerebentity',
            name='status',
            field=models.CharField(choices=[(1, 'Current'), (2, 'Unused')], default=1, max_length=10),
        ),
    ]
