# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-23 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_date_received', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, upload_to='cuil')),
            ],
        ),
        migrations.DeleteModel(
            name='Cuil',
        ),
    ]
