# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-30 12:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxpayerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date_received', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_app.TaxPayer')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
