# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-30 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0002_taxpayercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebentity',
            name='eb_country',
            field=models.CharField(choices=[('ARG', 'Argentina'), ('BR', 'Brazil'), ('USA', 'United states')], default=None, max_length=15, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='country',
            field=models.CharField(choices=[('ARG', 'Argentina'), ('BR', 'Brazil'), ('USA', 'United states')], max_length=50),
        ),
    ]
