# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-14 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0002_auto_20191011_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayer',
            name='taxpayer_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
