# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-29 19:29
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier_app', '0002_auto_20191015_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAddress',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('number', models.CharField(max_length=10, verbose_name='Number')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip code')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical address',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBankAccount',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('bank_account_number', models.CharField(db_index=True, max_length=60, verbose_name='Bank account number')),
                ('bank_info', models.IntegerField(choices=[(16, 'CITIBANK N.A.'), (7, 'BANCO DE GALICIA Y BUENOS AIRES S.A.'), (11, 'BANCO DE LA NACION ARGENTINA'), (17, 'BBVA BANCO FRANCES S.A.')], verbose_name='Bank name')),
                ('bank_cbu_file', models.TextField(max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Bank account certificate')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bank account',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTaxPayer',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('workday_id', models.CharField(max_length=200)),
                ('business_name', models.CharField(max_length=200, verbose_name='Business name')),
                ('taxpayer_state', models.CharField(choices=[('APPROVED', 'Approved'), ('CHANGE REQUIRED', 'Change required'), ('PENDING', 'Pending'), ('DENIED', 'Denied')], default='PENDING', max_length=200)),
                ('country', models.CharField(default='AR', max_length=50)),
                ('taxpayer_date', models.DateField(blank=True, editable=False, verbose_name='Creation date')),
                ('taxpayer_comments', models.CharField(blank=True, max_length=200, null=True, verbose_name='Comments')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical tax payer',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTaxPayerArgentina',
            fields=[
                ('taxpayer_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='supplier_app.TaxPayer')),
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('workday_id', models.CharField(max_length=200)),
                ('business_name', models.CharField(max_length=200, verbose_name='Business name')),
                ('taxpayer_state', models.CharField(choices=[('APPROVED', 'Approved'), ('CHANGE REQUIRED', 'Change required'), ('PENDING', 'Pending'), ('DENIED', 'Denied')], default='PENDING', max_length=200)),
                ('country', models.CharField(default='AR', max_length=50)),
                ('taxpayer_date', models.DateField(blank=True, editable=False, verbose_name='Creation date')),
                ('taxpayer_comments', models.CharField(blank=True, max_length=200, null=True, verbose_name='Comments')),
                ('cuit', models.CharField(max_length=20)),
                ('payment_type', models.CharField(choices=[('BANK', 'Bank')], default='BANK', max_length=20, verbose_name='Payment type')),
                ('payment_term', models.IntegerField(choices=[(15, '15 days'), (30, '30 days')], default=15, verbose_name='Payment term')),
                ('afip_registration_file', models.TextField(max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='AFIP registration certificate')),
                ('witholding_taxes_file', models.TextField(max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Certificate of no tax withholding of IVA, income or SUSS')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical tax payer argentina',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='Zip code'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_account_number',
            field=models.CharField(max_length=60, unique=True, verbose_name='Bank account number'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_cbu_file',
            field=models.FileField(upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Bank account certificate'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='business_name',
            field=models.CharField(max_length=200, verbose_name='Business name'),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='taxpayer_comments',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='taxpayer_date',
            field=models.DateField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='taxpayer_state',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('CHANGE REQUIRED', 'Change required'), ('PENDING', 'Pending'), ('DENIED', 'Denied')], default='PENDING', max_length=200),
        ),
        migrations.AlterField(
            model_name='taxpayerargentina',
            name='payment_term',
            field=models.IntegerField(choices=[(15, '15 days'), (30, '30 days')], default=15, verbose_name='Payment term'),
        ),
        migrations.AlterField(
            model_name='taxpayerargentina',
            name='payment_type',
            field=models.CharField(choices=[('BANK', 'Bank')], default='BANK', max_length=20, verbose_name='Payment type'),
        ),
        migrations.AddField(
            model_name='historicaltaxpayerargentina',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier_app.Company'),
        ),
        migrations.AddField(
            model_name='historicaltaxpayerargentina',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltaxpayer',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier_app.Company'),
        ),
        migrations.AddField(
            model_name='historicaltaxpayer',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbankaccount',
            name='taxpayer',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier_app.TaxPayer'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='taxpayer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier_app.TaxPayer'),
        ),
    ]
