# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-24 15:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0002_auto_20191015_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='Zip code'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_account_number',
            field=models.CharField(max_length=60, unique=True, verbose_name='Bank account number'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_cbu_file',
            field=models.FileField(upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Bank account certificate'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='business_name',
            field=models.CharField(max_length=200, verbose_name='Business name'),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='taxpayer_comments',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='taxpayer_date',
            field=models.DateField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='taxpayer_state',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('CHANGE REQUIRED', 'Change required'), ('PENDING', 'Pending'), ('DENIED', 'Denied')], default='PENDING', max_length=200),
        ),
        migrations.AlterField(
            model_name='taxpayerargentina',
            name='payment_term',
            field=models.IntegerField(choices=[(15, '15 days'), (30, '30 days')], default=15, verbose_name='Payment term'),
        ),
        migrations.AlterField(
            model_name='taxpayerargentina',
            name='payment_type',
            field=models.CharField(choices=[('BANK', 'Bank')], default='BANK', max_length=20, verbose_name='Payment type'),
        ),
    ]
