# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-28 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0003_auto_20191024_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayer',
            name='eb_entity',
            field=models.CharField(choices=[('EB_ARG', 'Eventbrite ARG'), ('EB_USA', 'Eventbrite USA'), ('EB_BR', 'Eventbrite BR')], default='EB_ARG', max_length=15, verbose_name='Bill to'),
        ),
    ]
