# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-30 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0003_auto_20191030_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayer',
            name='country',
            field=models.CharField(choices=[('ARG', 'Argentina'), ('BR', 'Brazil'), ('USA', 'United states')], max_length=50, verbose_name='Country'),
        ),
    ]
