# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-04 17:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0003_merge_20191101_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_cbu_file',
            field=models.FileField(upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), django.core.validators.MaxValueValidator(26214400)], verbose_name='Bank account certificate'),
        ),
        migrations.AlterField(
            model_name='historicalbankaccount',
            name='bank_cbu_file',
            field=models.TextField(max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), django.core.validators.MaxValueValidator(26214400)], verbose_name='Bank account certificate'),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='afip_registration_file',
            field=models.TextField(max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), django.core.validators.MaxValueValidator(26214400)], verbose_name='AFIP registration certificate'),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='witholding_taxes_file',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), django.core.validators.MaxValueValidator(26214400)], verbose_name='Certificate of no tax withholding of Tax liens, income or SUSS'),
        ),
        migrations.AlterField(
            model_name='taxpayerargentina',
            name='afip_registration_file',
            field=models.FileField(upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), django.core.validators.MaxValueValidator(26214400)], verbose_name='AFIP registration certificate'),
        ),
        migrations.AlterField(
            model_name='taxpayerargentina',
            name='witholding_taxes_file',
            field=models.FileField(blank=True, null=True, upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), django.core.validators.MaxValueValidator(26214400)], verbose_name='Certificate of no tax withholding of Tax liens, income or SUSS'),
        ),
    ]
