# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-29 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0003_auto_20191024_1432'),
        ('supplier_app', '0003_auto_20191024_1542'),
    ]

    operations = [
    ]
