# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-28 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0004_taxpayer_eb_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eb_name', models.CharField(max_length=15, verbose_name='Eventbrite entity name')),
            ],
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='eb_entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supplier_app.EBEntity', verbose_name='Bill to'),
        ),
    ]
