# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-30 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0004_auto_20191030_1537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaxPayerXEBEntity',
            new_name='TaxPayerEBEntity',
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('ARG', 'Argentina'), ('BR', 'Brazil'), ('USA', 'United states')], max_length=50, verbose_name='Country'),
        ),
    ]
