# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-05 19:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0005_auto_20191104_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[A-Z]{1}[a-z]')], verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[A-Z]{1}[a-z]')], verbose_name='City'),
        ),
    ]
