# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-28 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0005_auto_20191028_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxpayer',
            name='eb_entity',
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='eb_entity',
            field=models.ManyToManyField(default=1, to='supplier_app.EBEntity', verbose_name='Bill to'),
        ),
    ]
