# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-28 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0006_auto_20191028_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayer',
            name='eb_entity',
            field=models.ManyToManyField(to='supplier_app.EBEntity', verbose_name='Bill to'),
        ),
    ]
