# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-05 20:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0008_auto_20191105_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_account_number',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator('[0-9]'), django.core.validators.MinLengthValidator(22), django.core.validators.MaxLengthValidator(22)], verbose_name='Bank account number'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='historicalbankaccount',
            name='bank_account_number',
            field=models.CharField(db_index=True, max_length=60, validators=[django.core.validators.RegexValidator('[0-9]'), django.core.validators.MinLengthValidator(22), django.core.validators.MaxLengthValidator(22)], verbose_name='Bank account number'),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='cuit',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator('[0-9]+'), django.core.validators.MaxLengthValidator(11), django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='taxpayerargentina',
            name='cuit',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('[0-9]+'), django.core.validators.MaxLengthValidator(11), django.core.validators.MinLengthValidator(11)]),
        ),
    ]
