# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-05 20:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0009_auto_20191105_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='cuit',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator('[0-9]+', code='invalid_cuit', message='CIUT must have only numbers'), django.core.validators.MaxLengthValidator(11), django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='taxpayerargentina',
            name='cuit',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('[0-9]+', code='invalid_cuit', message='CIUT must have only numbers'), django.core.validators.MaxLengthValidator(11), django.core.validators.MinLengthValidator(11)]),
        ),
    ]
