# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-05 20:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0010_auto_20191105_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_account_number',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', code='invalid_bank_number', message='Bank account must only have numbers'), django.core.validators.MinLengthValidator(22), django.core.validators.MaxLengthValidator(22)], verbose_name='Bank account number'),
        ),
        migrations.AlterField(
            model_name='historicalbankaccount',
            name='bank_account_number',
            field=models.CharField(db_index=True, max_length=60, validators=[django.core.validators.RegexValidator('^[0-9]+$', code='invalid_bank_number', message='Bank account must only have numbers'), django.core.validators.MinLengthValidator(22), django.core.validators.MaxLengthValidator(22)], verbose_name='Bank account number'),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='cuit',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+$', code='invalid_cuit', message='CUIT must have only numbers'), django.core.validators.MaxLengthValidator(11), django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='taxpayerargentina',
            name='cuit',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', code='invalid_cuit', message='CUIT must have only numbers'), django.core.validators.MaxLengthValidator(11), django.core.validators.MinLengthValidator(11)]),
        ),
    ]
