# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-06 12:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0011_auto_20191105_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='cuit',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+$', code='invalid_cuit', message='CUIT must only have numbers'), django.core.validators.MaxLengthValidator(11), django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='taxpayerargentina',
            name='cuit',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', code='invalid_cuit', message='CUIT must only have numbers'), django.core.validators.MaxLengthValidator(11), django.core.validators.MinLengthValidator(11)]),
        ),
    ]
