# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-06 12:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0012_auto_20191106_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-z][A-Z]*$')], verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-z][A-Z]*$')], verbose_name='City'),
        ),
    ]
