# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-06 14:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import utils.file_validator


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0013_auto_20191106_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltaxpayer',
            name='taxpayer_comments',
        ),
        migrations.RemoveField(
            model_name='historicaltaxpayerargentina',
            name='taxpayer_comments',
        ),
        migrations.RemoveField(
            model_name='taxpayer',
            name='taxpayer_comments',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('\\D', code='invalid_city', message='City name must only have letters')], verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_cbu_file',
            field=models.FileField(upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.file_validator.FileSizeValidator(code='invalid_file_size', limit_size=26214400)], verbose_name='Bank account certificate'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='city',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='state',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('\\D', code='invalid_city', message='City name must only have letters')], verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='historicalbankaccount',
            name='bank_cbu_file',
            field=models.TextField(max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.file_validator.FileSizeValidator(code='invalid_file_size', limit_size=26214400)], verbose_name='Bank account certificate'),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='afip_registration_file',
            field=models.TextField(max_length=100, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.file_validator.FileSizeValidator(code='invalid_file_size', limit_size=26214400)], verbose_name='AFIP registration certificate'),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='witholding_taxes_file',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.file_validator.FileSizeValidator(code='invalid_file_size', limit_size=26214400)], verbose_name='Certificate of no tax withholding of Tax liens, income or SUSS'),
        ),
        migrations.AlterField(
            model_name='taxpayerargentina',
            name='afip_registration_file',
            field=models.FileField(upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.file_validator.FileSizeValidator(code='invalid_file_size', limit_size=26214400)], verbose_name='AFIP registration certificate'),
        ),
        migrations.AlterField(
            model_name='taxpayerargentina',
            name='witholding_taxes_file',
            field=models.FileField(blank=True, null=True, upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.file_validator.FileSizeValidator(code='invalid_file_size', limit_size=26214400)], verbose_name='Certificate of no tax withholding of Tax liens, income or SUSS'),
        ),
    ]
