# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-13 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0015_auto_20191111_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaxpayer',
            name='workday_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='workday_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='workday_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
