# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-13 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0016_auto_20191113_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaladdress',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalbankaccount',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayer',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
