# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-14 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0016_auto_20191113_1702'),
        ('supplier_app', '0015_merge_20191112_1509'),
    ]

    operations = [
    ]
