# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-28 19:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import utils.file_validator


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0017_auto_20191113_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaxpayerargentina',
            name='afip_no_retention_taxes_file',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.file_validator.FileSizeValidator(code='invalid_file_size', limit_size=26214400)], verbose_name='AFIP No Retention'),
        ),
        migrations.AddField(
            model_name='historicaltaxpayerargentina',
            name='iibb_no_retention_taxes_file',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.file_validator.FileSizeValidator(code='invalid_file_size', limit_size=26214400)], verbose_name='IIBB No Retention'),
        ),
        migrations.AddField(
            model_name='historicaltaxpayerargentina',
            name='iibb_registration_file',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.file_validator.FileSizeValidator(code='invalid_file_size', limit_size=26214400)], verbose_name='IIBB registration certificate'),
        ),
        migrations.AddField(
            model_name='taxpayerargentina',
            name='afip_no_retention_taxes_file',
            field=models.FileField(blank=True, null=True, upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.file_validator.FileSizeValidator(code='invalid_file_size', limit_size=26214400)], verbose_name='AFIP No Retention'),
        ),
        migrations.AddField(
            model_name='taxpayerargentina',
            name='iibb_no_retention_taxes_file',
            field=models.FileField(blank=True, null=True, upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.file_validator.FileSizeValidator(code='invalid_file_size', limit_size=26214400)], verbose_name='IIBB No Retention'),
        ),
        migrations.AddField(
            model_name='taxpayerargentina',
            name='iibb_registration_file',
            field=models.FileField(blank=True, null=True, upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.file_validator.FileSizeValidator(code='invalid_file_size', limit_size=26214400)], verbose_name='IIBB registration certificate'),
        ),
        migrations.AddField(
            model_name='historicaltaxpayerargentina',
            name='taxpayer_condition',
            field=models.CharField(
                choices=[('monotributista', 'Monotributista'), ('responsable_inscripto', 'Responsable Inscripto')],
                default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='taxpayerargentina',
            name='taxpayer_condition',
            field=models.CharField(
                choices=[('monotributista', 'Monotributista'), ('responsable_inscripto', 'Responsable Inscripto')],
                default=1, max_length=30),
        ),
    ]
