# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-29 16:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier_app', '0018_auto_20200428_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Contact person')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('website', models.CharField(max_length=100, verbose_name='Web site',blank=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_app.Address')),
                ('taxpayer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supplier_app.TaxPayer')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalContactInformation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Contact person')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('website', models.CharField(max_length=100, verbose_name='Web site', blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('address', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier_app.Address')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('taxpayer', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier_app.TaxPayer')),
            ],
            options={
                'verbose_name': 'historical contact information',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
