# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-05 20:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0020_auto_20200430_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_account_type',
            field=models.IntegerField(choices=[(1, 'Caja de Ahorro'), (2, 'Cuenta corriente')], default=None, verbose_name='Account type'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_beneficiary',
            field=models.CharField(default=None, max_length=60, verbose_name='Beneficiary'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_transaction_type',
            field=models.IntegerField(choices=[(1, 'Transferencia')], default=None, verbose_name='Transaction type'),
        ),
        migrations.AddField(
            model_name='historicalbankaccount',
            name='bank_account_type',
            field=models.IntegerField(choices=[(1, 'Caja de Ahorro'), (2, 'Cuenta corriente')], default=None, verbose_name='Account type'),
        ),
        migrations.AddField(
            model_name='historicalbankaccount',
            name='bank_beneficiary',
            field=models.CharField(default=None, max_length=60, verbose_name='Beneficiary'),
        ),
        migrations.AddField(
            model_name='historicalbankaccount',
            name='bank_transaction_type',
            field=models.IntegerField(choices=[(1, 'Transferencia')], default=None, verbose_name='Transaction type'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('AR', 'Argentina')], max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_account_number',
            field=models.CharField(max_length=22, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', code='invalid_bank_number', message='Bank account must only have numbers'), django.core.validators.MinLengthValidator(22), django.core.validators.MaxLengthValidator(22)], verbose_name='Bank account number'),
        ),
        migrations.AlterField(
            model_name='ebentity',
            name='eb_country',
            field=models.CharField(choices=[('AR', 'Argentina')], default=None, max_length=15, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='country',
            field=models.CharField(choices=[('AR', 'Argentina')], max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='historicalbankaccount',
            name='bank_account_number',
            field=models.CharField(db_index=True, max_length=22, validators=[django.core.validators.RegexValidator('^[0-9]+$', code='invalid_bank_number', message='Bank account must only have numbers'), django.core.validators.MinLengthValidator(22), django.core.validators.MaxLengthValidator(22)], verbose_name='Bank account number'),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayer',
            name='country',
            field=models.CharField(choices=[('AR', 'Argentina')], max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='country',
            field=models.CharField(choices=[('AR', 'Argentina')], max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='taxpayer_condition',
            field=models.CharField(choices=[('monotributista', 'Monotributista'), ('responsable_inscripto', 'Responsable Inscripto')], max_length=100, verbose_name='Taxpayer Condition'),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='country',
            field=models.CharField(choices=[('AR', 'Argentina')], max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='taxpayerargentina',
            name='taxpayer_condition',
            field=models.CharField(choices=[('monotributista', 'Monotributista'), ('responsable_inscripto', 'Responsable Inscripto')], max_length=100, verbose_name='Taxpayer Condition'),
        ),
    ]
