# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-04 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier_app', '0020_auto_20200430_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountArgentina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.IntegerField(choices=[(1, 'Transferencia')], verbose_name='Payment type')),
                ('account_type', models.IntegerField(choices=[(1, 'Caja de Ahorro'), (2, 'Cuenta corriente')], verbose_name='Account type')),
                ('beneficiary', models.CharField(max_length=60, verbose_name='Beneficiary')),
                ('bank_account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supplier_app.BankAccount')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBankAccountArgentina',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('payment_type', models.IntegerField(choices=[(1, 'Transferencia')], verbose_name='Payment type')),
                ('account_type', models.IntegerField(choices=[(1, 'Caja de Ahorro'), (2, 'Cuenta corriente')], verbose_name='Account type')),
                ('beneficiary', models.CharField(max_length=60, verbose_name='Beneficiary')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_account', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier_app.BankAccount')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bank account argentina',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('AR', 'Argentina')], max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='ebentity',
            name='eb_country',
            field=models.CharField(choices=[('AR', 'Argentina')], default=None, max_length=15, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='country',
            field=models.CharField(choices=[('AR', 'Argentina')], max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayer',
            name='country',
            field=models.CharField(choices=[('AR', 'Argentina')], max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='country',
            field=models.CharField(choices=[('AR', 'Argentina')], max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='taxpayer_condition',
            field=models.CharField(choices=[('monotributista', 'Monotributista'), ('responsable_inscripto', 'Responsable Inscripto')], max_length=100, verbose_name='Taxpayer Condition'),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='country',
            field=models.CharField(choices=[('AR', 'Argentina')], max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='taxpayerargentina',
            name='taxpayer_condition',
            field=models.CharField(choices=[('monotributista', 'Monotributista'), ('responsable_inscripto', 'Responsable Inscripto')], max_length=100, verbose_name='Taxpayer Condition'),
        ),
    ]
