# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-12 19:03
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.file_validator


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier_app', '0021_auto_20200505_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitingBuyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_app.Company')),
                ('inviting_buyer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('creation_date', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                
            ],
        ),

    ]
