# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-01 15:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import utils.file_validator


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0022_auto_20200512_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_account_type',
            field=models.IntegerField(choices=[(1, 'Saving account'), (2, 'Checking account')], verbose_name='Account type'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_transaction_type',
            field=models.IntegerField(choices=[(1, 'Bank transfer')], verbose_name='Transaction type'),
        ),
        migrations.AlterField(
            model_name='historicalbankaccount',
            name='bank_account_type',
            field=models.IntegerField(choices=[(1, 'Saving account'), (2, 'Checking account')], verbose_name='Account type'),
        ),
        migrations.AlterField(
            model_name='historicalbankaccount',
            name='bank_transaction_type',
            field=models.IntegerField(choices=[(1, 'Bank transfer')], verbose_name='Transaction type'),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayer',
            name='taxpayer_state',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('CHANGE REQUIRED', 'Change required'), ('PENDING', 'Pending'), ('DENIED', 'Denied'), ('CHANGES PENDING', 'Changes pending'), ('IN PROGRESS', 'In Progress')], default='PENDING', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayer',
            name='workday_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='cuit',
            field=models.CharField(db_index=True, max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]+$', code='invalid_cuit', message='CUIT must only have numbers'), django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='payment_term',
            field=models.IntegerField(choices=[(15, '15 days'), (30, '30 days')], verbose_name='Payment term'),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='taxpayer_state',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('CHANGE REQUIRED', 'Change required'), ('PENDING', 'Pending'), ('DENIED', 'Denied'), ('CHANGES PENDING', 'Changes pending'), ('IN PROGRESS', 'In Progress')], default='PENDING', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='witholding_suss_file',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.file_validator.FileSizeValidator(code='invalid_file_size', limit_size=26214400)], verbose_name='Certificate of no SUSS withholding'),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='witholding_taxes_file',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.file_validator.FileSizeValidator(code='invalid_file_size', limit_size=26214400)], verbose_name='Certificate of no income withholding'),
        ),
        migrations.AlterField(
            model_name='historicaltaxpayerargentina',
            name='workday_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invitingbuyer',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='taxpayer_state',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('CHANGE REQUIRED', 'Change required'), ('PENDING', 'Pending'), ('DENIED', 'Denied'), ('CHANGES PENDING', 'Changes pending'), ('IN PROGRESS', 'In Progress')], default='PENDING', max_length=200),
        ),
        migrations.AlterField(
            model_name='taxpayerargentina',
            name='cuit',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', code='invalid_cuit', message='CUIT must only have numbers'), django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='taxpayerargentina',
            name='witholding_suss_file',
            field=models.FileField(blank=True, null=True, upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.file_validator.FileSizeValidator(code='invalid_file_size', limit_size=26214400)], verbose_name='Certificate of no SUSS withholding'),
        ),
        migrations.AlterField(
            model_name='taxpayerargentina',
            name='witholding_taxes_file',
            field=models.FileField(blank=True, null=True, upload_to='file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), utils.file_validator.FileSizeValidator(code='invalid_file_size', limit_size=26214400)], verbose_name='Certificate of no income withholding'),
        ),
    ]
