# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-04 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0023_auto_20200601_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='EBEntityCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_app.Company')),
                ('eb_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_app.EBEntity')),
            ],
        ),
    ]
