# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-09 14:28
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier_app', '0025_auto_20200608_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountUnitedStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_number', models.CharField(max_length=22, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', code='invalid_bank_number', message='Bank account must only have numbers')], verbose_name='Bank account number')),
                ('bank_name', models.CharField(max_length=150, unique=True, verbose_name='Bank name')),
                ('bank_address', models.CharField(max_length=150, unique=True, verbose_name='Bank address')),
                ('bank_transaction_type', models.IntegerField(choices=[(1, 'Check'), (1, 'ACH'), (1, 'Wire')], verbose_name='Transaction type')),
                ('bank_account_type', models.IntegerField(choices=[(1, 'Saving account'), (2, 'Checking account')], verbose_name='Account type')),
                ('bank_beneficiary', models.CharField(default=None, max_length=60, verbose_name='Beneficiary')),
                ('routing_number', models.CharField(max_length=22, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', code='invalid_routing_number', message='Routing number must only have numbers')], verbose_name='Routing number')),
                ('remit_address', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supplier_app.Address')),
                ('taxpayer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supplier_app.TaxPayer')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBankAccountUnitedStates',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('bank_account_number', models.CharField(db_index=True, max_length=22, validators=[django.core.validators.RegexValidator('^[0-9]+$', code='invalid_bank_number', message='Bank account must only have numbers')], verbose_name='Bank account number')),
                ('bank_name', models.CharField(db_index=True, max_length=150, verbose_name='Bank name')),
                ('bank_address', models.CharField(db_index=True, max_length=150, verbose_name='Bank address')),
                ('bank_transaction_type', models.IntegerField(choices=[(1, 'Check'), (1, 'ACH'), (1, 'Wire')], verbose_name='Transaction type')),
                ('bank_account_type', models.IntegerField(choices=[(1, 'Saving account'), (2, 'Checking account')], verbose_name='Account type')),
                ('bank_beneficiary', models.CharField(default=None, max_length=60, verbose_name='Beneficiary')),
                ('routing_number', models.CharField(db_index=True, max_length=22, validators=[django.core.validators.RegexValidator('^[0-9]+$', code='invalid_routing_number', message='Routing number must only have numbers')], verbose_name='Routing number')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('remit_address', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier_app.Address')),
                ('taxpayer', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='supplier_app.TaxPayer')),
            ],
            options={
                'verbose_name': 'historical bank account united states',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
