# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-18 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_app', '0026_bankaccountunitedstates_historicalbankaccountunitedstates'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaxpayer',
            name='new_comment_from_ap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltaxpayer',
            name='new_comment_from_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltaxpayerargentina',
            name='new_comment_from_ap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltaxpayerargentina',
            name='new_comment_from_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltaxpayerunitedstates',
            name='new_comment_from_ap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltaxpayerunitedstates',
            name='new_comment_from_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='new_comment_from_ap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='new_comment_from_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_transaction_type',
            field=models.IntegerField(choices=[(1, 'Bank transfer')], verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='bankaccountunitedstates',
            name='bank_transaction_type',
            field=models.IntegerField(choices=[(1, 'Check'), (1, 'ACH'), (1, 'Wire')], verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='historicalbankaccount',
            name='bank_transaction_type',
            field=models.IntegerField(choices=[(1, 'Bank transfer')], verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='historicalbankaccountunitedstates',
            name='bank_transaction_type',
            field=models.IntegerField(choices=[(1, 'Check'), (1, 'ACH'), (1, 'Wire')], verbose_name='Payment method'),
        ),
    ]
