BBBB BBBB
BBBB BBBBBB
XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX

    BB BBBBBBBBBBBBBBBBBBBBB
        XXX XXXXXXXXXXXXXXXXX X
            XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
    BBBB
        XXX XXXXXXXXXXXXXXXX XXXXXXXXXX
            XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
    BBBBB

    BBB BBBB BB BBBBBBBBBBBBBB
        BB BBBB
            BBBBBBB BBBB BBBBBBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXX XXXXXXXX
                    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXXXX
            BBBB
                XXX XXXXXXXXXXXXXXXXXX
                    XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXXXX
            BBBBBBBBBB
        BBBBB
    BBBBBB

    BB BBBBBBBBBBBBBBBBB
        XXX XXXXXXXXXXXXXXXXXX
            XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX
        XXXXX
    BBBB
        XXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                XX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
    BBBBB
XXXXX