BBBB BBBB

XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
    BBBBBBBBBB
    BB BBBBBB BB BBBBBBBBBBBBBBBB
    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX
    BBBB
    XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XX
    BBBBB
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBB BB BBBBBBBBBBBBB BB BBBB
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBB BB BBBBBBBBBBBBB BB BBBB
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBB BB BBBBBBBBBBBBB BB BBBBBBB
          XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
          BBBBB

        XXXX
        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXX
        XXXXX
    XXXXXX
XXXXXXX
