BBBB BBBBBB
BBBB BBBB
XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX

    BB BBBBBBBBBBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXX XXXXXXX
        XX
    XXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Management') 
                XXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXXXXXXXXXXX
                            XX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                             gettext(u'Invoices') 
                    XXXX
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBXX
                        XX XXXXXXXXX XXXXXXXXXXXXXX gettext(u'Taxpayers') 
                    XXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXX
                            XX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Manage Admins') 
                    XXXX
                    BBBBB
            XXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Companies') 
                XXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBXXXX
                        XXXXXXXXX XXXXXXXXXXX XXXXXXXXXX gettext(u'See all') XXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXXXX
                            XXXXXXXXX XXXXXXX XXXXXXXXXX gettext(u'Create one') XXXX
                    BBBBB
                XXXXXX
            XXXXX
            BBBBB
        XXXXX
    XXXXXX

    
    BBBB  BBBBBBBBBBBBBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXX XXXXXXX
         gettext(u'Buyer') 
    XXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX

        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                     gettext(u'Companies') 
                XXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBXXXX
                        XXXXXXXXX XXXXXXXXXXX XXXXXXXXXX gettext(u'See all') XXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBXXXX
                            XXXXXXXXX XXXXXXX XXXXXXXXXX gettext(u'Create one') XXXX
                    BBBBB
                XXXXXX
            XXXXX
        BBBBB
        XXXXX
    XXXXXX
        
    BBBB
    XX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXX
        XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXX XXXXXXX
         gettext(u'Supplier') 
    XXXX

    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXXXX
                    XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX gettext(u'My Taxpayers') 
                XXXX
            XXXXX

            XXX XXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBXXXX
                    XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Invoices') XXXX
            XXXXX
            BB BBBBBBBB
            XXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    
                XXXX
                XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXX
                            XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX gettext(u'My Invoices') XXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
                        XX XXXXXXXXX XXXXXXX XXXXXXXXXX gettext(u'New Invoice') 
                    XXXX
                    BBBBB
                XXXXXX
            XXXXX
            BBBBB
        XXXXX
    XXXXXX
    BBBBB
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXX
        XXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX
                XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXX XXXXXXX XXXXXXXXXX 
                XXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBXX
                        XX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                         gettext(u'Log out') 
                    XXXX
                XXXXXX
            XXXXX
        XXXXX
    XXXXXX


XXXXXX
