BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBB
BBBB BBBBBB
BBBBBBBB

BBBBB BBBBBBB

BBBBBBB BBBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXX XXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX gettext(u'Contact Information') XXXXX
    XXXXXX
    XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBBBBBBB
                
                XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXX
                    XXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX
                        XXXXXXXBB BBBBBBBBBBBBBBBBBB gettext(u'Save') BBBB gettext(u'Request change') BBBBBXX
                    XX XXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
                         gettext(u'Cancel') 
                    XXXX
                XXXXXX
            XXXXXXX
        XXXXXX
    XXXXXX
XXXXXX


BBBBBBBB